# Generated by Django 5.0.14 on 2025-12-18 17:15

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import submissions.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_teacher', models.BooleanField(default=False, help_text='Designates whether this user is a teacher.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the project requirements')),
                ('requirements_file', models.FileField(blank=True, help_text='Optional: Upload project requirements document (PDF, DOCX)', null=True, upload_to='classroom_requirements/')),
                ('join_code', models.CharField(default=submissions.models.generate_join_code, editable=False, help_text='Unique code for students to join this classroom', max_length=8, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'is_teacher': True}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_classrooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom',
                'verbose_name_plural': 'Classrooms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of your project', max_length=200)),
                ('description', models.TextField(help_text='Describe your project, its features, and implementation details')),
                ('repository_url', models.URLField(help_text='GitHub or GitLab repository URL (required)', verbose_name='Repository URL')),
                ('deployed_url', models.URLField(blank=True, help_text='URL where your project is deployed (optional)', null=True, verbose_name='Deployed URL')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted')], default='DRAFT', max_length=10)),
                ('grade', models.PositiveSmallIntegerField(blank=True, help_text='Grade from 1 to 20', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('teacher_notes', models.TextField(blank=True, help_text='Feedback and notes from the teacher')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.classroom')),
                ('collaborators', models.ManyToManyField(help_text='Select team members from this classroom', related_name='project_collaborations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project Submission',
                'verbose_name_plural': 'Project Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClassroomMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='submissions.classroom')),
                ('student', models.ForeignKey(limit_choices_to={'is_teacher': False}, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Classroom Membership',
                'verbose_name_plural': 'Classroom Memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('classroom', 'student')},
            },
        ),
        migrations.AddConstraint(
            model_name='projectsubmission',
            constraint=models.UniqueConstraint(fields=('classroom', 'created_by'), name='unique_submission_per_student_per_classroom'),
        ),
    ]
