# Generated by Django 5.0.14 on 2025-12-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubmission',
            name='project_file',
            field=models.FileField(blank=True, help_text='Upload your project as a ZIP file (max 10MB)', null=True, upload_to='project_submissions/'),
        ),
        migrations.AddField(
            model_name='projectsubmission',
            name='submission_type',
            field=models.CharField(choices=[('URL', 'Repository URL'), ('FILE', 'File Upload')], default='URL', help_text='Choose to submit via GitHub URL or upload project file', max_length=10),
        ),
        migrations.AlterField(
            model_name='projectsubmission',
            name='repository_url',
            field=models.URLField(blank=True, help_text='GitHub or GitLab repository URL', null=True, verbose_name='Repository URL'),
        ),
    ]
