# Generated by Django 5.0.14 on 2025-12-18 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_projectsubmission_project_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsubmission',
            name='submission_type',
            field=models.CharField(choices=[('URL', 'Repository URL Only'), ('FILE', 'File Upload Only'), ('BOTH', 'Both URL and File')], default='URL', help_text='Choose how to submit your project', max_length=10),
        ),
    ]
